### PR TITLE
sendGraph: Get all peers using nearbyPath argument to getPeers

### PR DESCRIPTION
**Pull request by kyrias**
Currently not all peers will be found, since getPeers will only return a maximum of 8, so use nearbyPath to make sure we get them all.

### CODE REVIEW

**Comment by zielmicha** [comment]
Could you briefly describe how the `nearbyPath` argument works?

**Comment by kyrias** [comment]
Basically, the results of `getPeers` is sorted by the path. Giving the `nearbyPath` argument makes it get the nodes starting with that path. Then on the last peer it will return just the peer with that path.

**Comment by kyrias** [comment]
Hmm, though it seems some of my logic might be off.

```
get_peers: timed out on 0000.0000.7cb5.e237 (nearby 0000.0000.0000.001d), trying again. 2 tries remaining.
get_peers: timed out on 0000.0000.0000.da37 (nearby 0000.0000.0000.048c), trying again. 2 tries remaining.
get_peers: timed out on 0000.0000.7cb5.e237 (nearby 0000.0000.0000.001d), trying again. 2 tries remaining.
```

Semes like it it tried it over again, hmm...

**Comment by kyrias** [comment]
Can't figure out how that happened though. Can you?

**Comment by zielmicha** [comment]
`get_peers` may return peer with the same path it was asked for (2bad4d8b39).

**Comment by kyrias** [comment]
Oh right, crap, forgot to remove it, sorry. Will fix in a moment.

**Pull request merged**
